=== wallix/pylogsparser/normalizers/normalizer.dtd
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!ELEMENT normalizer (description?,authors?,tagTypes?,callbacks?,prerequisites?,patterns,commonTags?,finalCallbacks?)>
 <!-- The given name of the normalizer -->
 <!ATTLIST normalizer name CDATA #REQUIRED>
 <!-- The version of this normalizer -->
 <!ATTLIST normalizer version CDATA #REQUIRED>
 <!-- Compile the associated regexps with the UNICODE flag -->
 <!ATTLIST normalizer unicode (no|yes) "yes">
 <!-- Compile the associated regexps with the IGNORECASE flag -->
 <!ATTLIST normalizer ignorecase (no|yes) "yes">
 <!-- Patterns are multiline -->
 <!ATTLIST normalizer multiline (no|yes) "yes">
 <!-- how to match the pattern : "match" to match at the beginning of the sample,
      or "search" to match anywhere in the sample -->
 <!ATTLIST normalizer matchtype (match|search) "match">
 <!-- What tag will the patterns be applied to ? Set the value to "raw" for
      protocol normalizers, "body" for application or generic normalizers -->
 <!ATTLIST normalizer appliedTo CDATA #REQUIRED>
<!-- A set of descriptions, language is specified as the usual language code -->
 <!-- The service taxonomy, if relevant, of the normalizer. See README.rst -->
 <!ATTLIST normalizer taxonomy CDATA #IMPLIED>
  <!-- set to yes if a space in the patterns should be considered as a combination 
      of any whitespace character, for readability of the patterns.-->
 <!ATTLIST normalizer  expandWhitespaces (yes|no) "no">
<!ELEMENT description (localized_desc+)>
 <!ELEMENT localized_desc (#PCDATA)>
 <!ATTLIST localized_desc language CDATA #REQUIRED>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>

<!-- Here one can define specific regexp blocks (this should be rare, with 
     most cases being covered by default tagTypes.). Once extracted, the result
     is passed to the callbacks in order. -->
<!ELEMENT tagTypes (tagType+)>
<!ELEMENT tagType (description?,regexp)>
 <!-- the name of the tag type preferably in camelCase, for example
      "syslogDate", "EPOCH", "IP", etc -->
 <!ATTLIST tagType name CDATA #REQUIRED>
 <!-- The expected python type of the extracted value once the callbacks
      have been fired. Not used yet, might be in the future. -->
 <!ATTLIST tagType type (integer|float|basestring|datetime) "basestring">
<!-- the regular expression the data must match to qualify, for example
     "[A-Z][a-z]{2} [ 0-9]\d \d{2}:\d{2}:\d{2}" -->
<!ELEMENT regexp (#PCDATA)>
<!-- Python functions to call after the data has been extracted with the regular
     expression. The functions are called in order of definition.-->
<!ELEMENT callbacks (callback+)> 
<!ELEMENT callback (#PCDATA)>
 <!-- a name is REQUIRED as an attribute when defining the function, and
      unnecessary when associated to a tag definition. Instead, the name MUST be
      mentioned as text between the <callback> tags. -->
 <!ATTLIST callback name CDATA #IMPLIED>
<!-- does a tag need to match a value before we should apply this normalizer ? -->
<!ELEMENT prerequisites (prereqTag+)> 
<!ELEMENT prereqTag (#PCDATA)>
 <!ATTLIST prereqTag name CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>

<!-- Define the patterns associated to this normalizer. -->
<!ELEMENT patterns (pattern+)> 
<!ELEMENT pattern (description?,text,tags,commonTags?,examples?)>
 <!-- a handy name for the pattern. Patterns are applied in alphabetical order
      of names.-->
 <!ATTLIST pattern name CDATA #REQUIRED>
<!-- a meta description of the log line covered by this pattern, for example
     <SYSLOGCODE>SYSLOGDATE SOURCE PROGRAM\[PID\]: BODY
     Regular expressions' metacharacters are not escaped by default, to provide
     their full power without the hassle.-->
<!ELEMENT text (#PCDATA)> 
<!-- The type of pattern. The default if type is not specified
     is a regexp pattern. "type" attribute can be "csv" to force normalizer engine
     to use csv python module in order to extract fields. The meta description
     for a csv pattern type must be as follow DATE,IP,USER,BODY where fields
     will be substitute by defined tags.-->
 <!ATTLIST text type CDATA #IMPLIED>
<!-- If attribute "type" is "csv" this attribute is used to define the csv separator.
     By default separator is a comma.-->
 <!ATTLIST text separator CDATA #IMPLIED>
<!-- If attribute "type" is "csv" this attribute is used to define the csv quotechar.
     By default quotechar is a quote.-->
 <!ATTLIST text quotechar CDATA #IMPLIED>
<!-- a list of real-life examples that can be used for auto-generating some
     documentation and unit testing. -->
<!ELEMENT examples (example+)> 
 <!ELEMENT example (description?,text,expectedTags)>
<!-- a (non necessarily complete) list of tags this normalizer will extract
     from this example. These tags must be present after normalizing the
     example for this normalizer to be considered valid.-->
<!ELEMENT expectedTags (expectedTag+)> 
 <!ELEMENT expectedTag (#PCDATA)>
  <!ATTLIST expectedTag name CDATA #REQUIRED>
<!-- A list of tags associated to the meta description in the pattern. -->
<!ELEMENT tags (tag+)> 
<!ELEMENT tag (description?,substitute,callbacks?)>
<!-- The name of the tag, as it will appear in the WallixLog. 
     if the name starts with '__' it is considered a temporary value (typically
     processed in callbacks) that will therefore not appear after normalization.-->
 <!ATTLIST tag name CDATA #REQUIRED> 
 <!-- the tag type, used to determine the regular expression that will be
      substituted in the pattern. It must be either a built-in tagType,
      or one defined in the current tagTypes markup. Newly defined tagTypes
      take precedence over built-in ones in case of a naming conflict. -->
 <!ATTLIST tag tagType CDATA "Anything"> 
<!-- The string chain that will be replaced by the tagType's regular
     expression in the pattern. -->
<!ELEMENT substitute (#PCDATA)>

<!-- If necessary, define here tags that must be set even though they weren't
     found in the pattern. -->
<!ELEMENT commonTags (commonTag+)> 
<!ELEMENT commonTag (#PCDATA)>
 <!ATTLIST commonTag name CDATA #REQUIRED>
 
<!-- If necessary, add here calls to callbacks to execute after
     the regular normalization. An arbitrary value argument set to 
     None will be passed to the callback. -->
<!ELEMENT finalCallbacks (callback+)>

=== wallix/pylogsparser/normalizers/dhcpd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="DHCPd"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="body"
            taxonomy="address assignation">
    <description>
        <localized_desc language="en">This normalizer parses DHCPd messages.</localized_desc>
        <localized_desc language="fr">Ce normaliseur analyse les messages émis par les serveurs DHCPd.</localized_desc></description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <tagTypes>
        <tagType name="AnythingWithoutSpace" type="basestring">
            <description>
        <localized_desc language="en">Expression matching a single word or lexeme.</localized_desc>
        <localized_desc language="fr">Expression correspondant à un mot sans espace intersticiel.</localized_desc></description>
            <regexp>[^ ]+</regexp>
        </tagType>
        <tagType name="DHCPAction" type="basestring">
            <description>
        <localized_desc language="en">Expression matching the action notified by the DCHP daemon.</localized_desc>
        <localized_desc language="fr">Expression correspondant à l'action DHCP.</localized_desc></description>
            <regexp>DHCP[A-Z]+</regexp>
        </tagType>
    </tagTypes>
    <callbacks>
        <callback name="decode_action">
log["action"] = value[4:]
        </callback>
    </callbacks>
    <patterns>
        <pattern name="DHCPd-001-DISCOVER">
            <description>
        <localized_desc language="en">Generic DHCP discovery message.</localized_desc>
        <localized_desc language="fr">Structure générique d'un message de découverte DHCP.</localized_desc></description>
            <text>DHCPACTION from MACADDRESS via ADDRESS</text>
            <tags>
                <tag name="__dhcpaction" tagType="DHCPAction">
                    <substitute>DHCPACTION</substitute>
                    <callbacks>
                        <callback>decode_action</callback>
                    </callbacks>
                </tag>
                <tag name="source_mac" tagType="MACAddress">
                    <substitute>MACADDRESS</substitute>
                </tag>
                <tag name="via" tagType="AnythingWithoutSpace">
                    <substitute>ADDRESS</substitute>
                </tag>
            </tags>
            <examples>
                <example>
                    <text>DHCPDISCOVER from 02:1c:25:a3:32:76 via 183.213.184.122</text>
                    <expectedTags>
                        <expectedTag name="action">DISCOVER</expectedTag>
                        <expectedTag name="source_mac">02:1c:25:a3:32:76</expectedTag>
                        <expectedTag name="via">183.213.184.122</expectedTag>
                        <expectedTag name="taxonomy">address assignation</expectedTag>
                    </expectedTags>
                </example>
            </examples>
        </pattern>
        <pattern name="DHCPd-002-INFORM">
            <description>
        <localized_desc language="en">Generic DHCP inform message.</localized_desc>
        <localized_desc language="fr">Message générique informatif.</localized_desc></description>
            <text>DHCPACTION from IP</text>
            <tags>
                <tag name="__dhcpaction" tagType="DHCPAction">
                    <substitute>DHCPACTION</substitute>
                    <callbacks>
                        <callback>decode_action</callback>
                    </callbacks>
                </tag>
                <tag name="source_ip" tagType="IP">
                    <substitute>IP</substitute>
                </tag>
            </tags>
            <examples>
                <example>
                    <text>DHCPINFORM from 183.231.184.122</text>
                    <expectedTags>
                        <expectedTag name="action">INFORM</expectedTag>
                        <expectedTag name="source_ip">183.231.184.122</expectedTag>
                        <expectedTag name="taxonomy">address assignation</expectedTag>
                    </expectedTags>
                </example>
            </examples>
        </pattern>
        <pattern name="DHCPd-003-OTHERACTIONS">
            <description>
        <localized_desc language="en">Other DHCP messages : offer, request, acknowledge, non-acknowledge, decline, release.</localized_desc>
        <localized_desc language="fr">Autres messages DHCP : offre de bail, requête, confirmation, réfutation, refus, libération de bail.</localized_desc></description>
            <text>DHCPACTION [a-z]+ IP [a-z]+ MACADDRESS via VIA</text>
            <tags>
                <tag name="__dhcpaction" tagType="DHCPAction">
                    <substitute>DHCPACTION</substitute>
                    <callbacks>
                        <callback>decode_action</callback>
                    </callbacks>
                </tag>
                <tag name="source_ip" tagType="IP">
                    <substitute>IP</substitute>
                </tag>
                <tag name="source_mac" tagType="MACAddress">
                    <substitute>MACADDRESS</substitute>
                </tag>
                <tag name="via" tagType="AnythingWithoutSpace">
                    <substitute>VIA</substitute>
                </tag>
            </tags>
            <examples>
                <example>
                    <text>DHCPOFFER on 183.231.184.122 to 00:13:ec:1c:06:5b via 183.213.184.122</text>
                    <expectedTags>
                        <expectedTag name="action">OFFER</expectedTag>
                        <expectedTag name="source_ip">183.231.184.122</expectedTag>
                        <expectedTag name="source_mac">00:13:ec:1c:06:5b</expectedTag>
                        <expectedTag name="via">183.213.184.122</expectedTag>
                        <expectedTag name="taxonomy">address assignation</expectedTag>
                    </expectedTags>
                </example>
                <example>
                    <text>DHCPREQUEST for 183.231.184.122 from 00:13:ec:1c:06:5b via 183.213.184.122</text>
                    <expectedTags>
                        <expectedTag name="action">REQUEST</expectedTag>
                        <expectedTag name="source_ip">183.231.184.122</expectedTag>
                        <expectedTag name="source_mac">00:13:ec:1c:06:5b</expectedTag>
                        <expectedTag name="via">183.213.184.122</expectedTag>
                        <expectedTag name="taxonomy">address assignation</expectedTag>
                    </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
</normalizer>

=== wallix/pylogsparser/normalizers/cisco-asa_header.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogsparser - Logs parsers python library                 -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="cisco-asa_header"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="raw">
 <description>
  <localized_desc language="en">This normalizer parses logs received via the syslog
   export facility from a Cisco ASA. The normalizer supports Cisco ASA version 8.4.
   The standard export format (No EMBLEM format) with "Device ID" and "timestamp" options must be
   selected for this normalizer.
  </localized_desc>
  <localized_desc language="fr">Ce normaliseur reconnaît les logs Cisco ASA exportés via
   la facilité syslog. Ce normaliseur est compatible avec la version 8.4 de l'IOS Cisco ASA.
   Le format d'export standard (Non EMBLEM) doit être sélectionné avec les options "Device ID" et
   "timestamp".
  </localized_desc>
 </description>
 <authors>
  <author>fbo@wallix.com</author>
 </authors>
 <tagTypes>
  <tagType name="syslogPriority" type="integer">
   <description>
    <localized_desc language="en">Expression matching a syslog line priority, defined as 8*facility + severity.</localized_desc>
    <localized_desc language="fr">Expression correspondant à la priorité du message, suivant la formule 8 x facilité + gravité.</localized_desc>
   </description>
   <regexp>\d{1,3}</regexp>
  </tagType>
  <tagType name="dateASA1" type="datetime">
   <description>
    <localized_desc language="en">Expression matching a date in the DDD MMM dd hh:mm:ss YYYY format.</localized_desc>
    <localized_desc language="fr">Expression correspondant à la date au format DDD MMM dd hh:mm:ss YYYY.</localized_desc>
   </description>
   <regexp>[A-Z]{1}[a-z]{2} [0-9]{1,2} [0-9]{4} \d{2}:\d{2}:\d{2}</regexp>
  </tagType>
  <tagType name="deviceID" type="basestring">
   <description>
    <localized_desc language="en">Expression matching the device ID.</localized_desc>
    <localized_desc language="fr">Expression correspondant à l'identifiant de l'équipement.</localized_desc>
   </description>
   <regexp>[^: ]+</regexp>
  </tagType>
 </tagTypes>
 <callbacks>
  <callback name="decode_priority">
# define facilities
FACILITIES = { 0: "kernel",
               1: "user",
               2: "mail",
               3: "daemon",
               4: "auth",
               5: "syslog",
               6: "print",
               7: "news",
               8: "uucp",
               9: "ntp",
               10: "secure",
               11: "ftp",
               12: "ntp",
               13: "audit",
               14: "alert",
               15: "ntp" }
for i in range(0, 8):
    FACILITIES[i+16] = "local%d" % i

# define severities
SEVERITIES = { 0: "emerg",
               1: "alert",
               2: "crit",
               3: "error",
               4: "warn",
               5: "notice",
               6: "info",
               7: "debug" }
facility = int(value) / 8
severity = int(value) % 8
if facility not in FACILITIES or severity not in SEVERITIES:
    raise ValueError('facility or severity is out of range')
log["facility"] = "%s" % FACILITIES[facility]
log["severity"] = "%s" % SEVERITIES[severity]
log["facility_code"] = "%d" % facility
log["severity_code"] = "%d" % severity
  </callback>
  <callback name="decode_asa_severity">
SEVERITIES = { 0: "emerg",
               1: "alert",
               2: "crit",
               3: "error",
               4: "warn",
               5: "notice",
               6: "info",
               7: "debug" }
log["severity_code"] = "%s" % str(value)
log["severity"] = "%s" % SEVERITIES[int(value)]
  </callback>
 </callbacks>
 <patterns>
  <pattern name="asa-001">
   <description>
    <localized_desc language="en">Expression matching the Cisco ASA Syslog header</localized_desc>
    <localized_desc language="fr">Expression correspondant à l'en-tête Syslog d'un équipement Cisco ASA</localized_desc>
   </description>
   <text>&lt;PRIORITY&gt;DATE SOURCE : %ASA-SEVERITY-MNEMONIC: BODY</text>
   <tags>
    <tag name="__priority" tagType="syslogPriority">
     <description>
      <localized_desc language="en">the log's priority</localized_desc>
      <localized_desc language="fr">la priorité du log, égale à 8 x facilité + gravité</localized_desc>
     </description>
     <substitute>PRIORITY</substitute>
     <callbacks>
      <callback>decode_priority</callback>
     </callbacks>
    </tag>
    <tag name="date" tagType="dateASA1">
     <description>
     <localized_desc language="en">the log's date</localized_desc>
     <localized_desc language="fr">l'horodatage du log</localized_desc></description>
     <substitute>DATE</substitute>
     <callbacks>
      <callback>MMM dd YYYY hh:mm:ss</callback>
     </callbacks>
    </tag>
    <tag name="source" tagType="deviceID">
     <description>
     <localized_desc language="en">the log's source (device ID)</localized_desc>
     <localized_desc language="fr">la source du log (device ID)</localized_desc></description>
     <substitute>SOURCE</substitute>
    </tag>
    <tag name="__cseverity" tagType="Integer">
     <description>
     <localized_desc language="en">the log's severity</localized_desc>
     <localized_desc language="fr">la gravité du log</localized_desc>
     </description>
     <substitute>SEVERITY</substitute>
     <callbacks>
      <callback>decode_asa_severity</callback>
     </callbacks>
    </tag>
    <tag name="event_id" tagType="Integer">
     <description>
     <localized_desc language="en">the Cisco ID of the event</localized_desc>
     <localized_desc language="fr">l'identifiant Cisco de l'événement</localized_desc>
     </description>
     <substitute>MNEMONIC</substitute>
    </tag>
    <tag name="body" tagType="Anything">
     <description>
     <localized_desc language="en">the actual event message</localized_desc>
     <localized_desc language="fr">le message décrivant l'événement</localized_desc>
     </description>
     <substitute>BODY</substitute>
    </tag>
   </tags>
   <commonTags>
    <commonTag name="program">cisco-asa</commonTag>
   </commonTags>
   <examples>
    <example>
     <text>&lt;165&gt;Jan 25 2012 18:31:09 ciscoasa : %ASA-5-111008: User 'enable_15' executed the 'logging host inside2 192.168.30.2 6/11508' command.</text>
     <expectedTags>
      <expectedTag name="facility">local4</expectedTag>
      <expectedTag name="severity">notice</expectedTag>
      <expectedTag name="severity_code">5</expectedTag>
      <expectedTag name="source">ciscoasa</expectedTag>
      <expectedTag name="date">2012-01-25 18:31:09</expectedTag>
      <expectedTag name="event_id">111008</expectedTag>
      <expectedTag name="program">cisco-asa</expectedTag>
      <expectedTag name="body">User 'enable_15' executed the 'logging host inside2 192.168.30.2 6/11508' command.</expectedTag>
     </expectedTags>
    </example>
   </examples>
  </pattern>
 </patterns>
</normalizer>

=== wallix/pylogsparser/normalizers/UserAgent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="UserAgent"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="useragent">
    <description>
        <localized_desc language="en">This normalizer extracts additional information from the useragent field in a HTTP request.</localized_desc>
        <localized_desc language="fr">Ce normaliseur extrait des données supplémentaires du champ useragent présent dans les requêtes HTTP.</localized_desc>
    </description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <callbacks>
        <callback name="findBot">
m = extras.robot_regex.search(value)
if m:
    log["search_engine_bot"] = m.group().lower()
</callback>
        <callback name="guessOS">
known_os = {"Mac OS" : "Mac/Apple",
            "Windows" : "Windows",
            "Linux" : "Linux"}
guess = "unknown"
for i,j in known_os.items():
    if i in value:
        guess = j
        break
log['source_os'] = guess
</callback>
    </callbacks>
    <patterns>
        <pattern name="UseragentPattern">
            <text>USERAGENT</text>
            <tags>
                <tag name="__ua" tagType="Anything">
                    <substitute>USERAGENT</substitute>
                    <callbacks>
                        <callback>findBot</callback>
                        <callback>guessOS</callback>
                    </callbacks>
                </tag>
            </tags>
            <examples>
                <example>
                     <text>Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)</text>
                     <expectedTags>
                          <expectedTag name="search_engine_bot">baiduspider</expectedTag>
                          <expectedTag name="source_os">unknown</expectedTag>
                     </expectedTags>
                </example>
                <example>
                     <text>Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10</text>
                     <expectedTags>
                          <expectedTag name="source_os">Mac/Apple</expectedTag>
                     </expectedTags>
                </example>
                <example>
                     <text>Nokia6680/1.0 (4.04.07) SymbianOS/8.0 Series60/2.6 Profile/MIDP-2.0 Configuration/CLDC-1.1</text>
                     <expectedTags>
                          <expectedTag name="source_os">unknown</expectedTag>
                     </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
</normalizer>
