=== wallix/pylogsparser/normalizers/normalizer.dtd
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!ELEMENT normalizer (description?,authors?,tagTypes?,callbacks?,prerequisites?,patterns,commonTags?,finalCallbacks?)>
 <!-- The given name of the normalizer -->
 <!ATTLIST normalizer name CDATA #REQUIRED>
 <!-- The version of this normalizer -->
 <!ATTLIST normalizer version CDATA #REQUIRED>
 <!-- Compile the associated regexps with the UNICODE flag -->
 <!ATTLIST normalizer unicode (no|yes) "yes">
 <!-- Compile the associated regexps with the IGNORECASE flag -->
 <!ATTLIST normalizer ignorecase (no|yes) "yes">
 <!-- Patterns are multiline -->
 <!ATTLIST normalizer multiline (no|yes) "yes">
 <!-- how to match the pattern : "match" to match at the beginning of the sample,
      or "search" to match anywhere in the sample -->
 <!ATTLIST normalizer matchtype (match|search) "match">
 <!-- What tag will the patterns be applied to ? Set the value to "raw" for
      protocol normalizers, "body" for application or generic normalizers -->
 <!ATTLIST normalizer appliedTo CDATA #REQUIRED>
<!-- A set of descriptions, language is specified as the usual language code -->
 <!-- The service taxonomy, if relevant, of the normalizer. See README.rst -->
 <!ATTLIST normalizer taxonomy CDATA #IMPLIED>
  <!-- set to yes if a space in the patterns should be considered as a combination 
      of any whitespace character, for readability of the patterns.-->
 <!ATTLIST normalizer  expandWhitespaces (yes|no) "no">
<!ELEMENT description (localized_desc+)>
 <!ELEMENT localized_desc (#PCDATA)>
 <!ATTLIST localized_desc language CDATA #REQUIRED>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>

<!-- Here one can define specific regexp blocks (this should be rare, with 
     most cases being covered by default tagTypes.). Once extracted, the result
     is passed to the callbacks in order. -->
<!ELEMENT tagTypes (tagType+)>
<!ELEMENT tagType (description?,regexp)>
 <!-- the name of the tag type preferably in camelCase, for example
      "syslogDate", "EPOCH", "IP", etc -->
 <!ATTLIST tagType name CDATA #REQUIRED>
 <!-- The expected python type of the extracted value once the callbacks
      have been fired. Not used yet, might be in the future. -->
 <!ATTLIST tagType type (integer|float|basestring|datetime) "basestring">
<!-- the regular expression the data must match to qualify, for example
     "[A-Z][a-z]{2} [ 0-9]\d \d{2}:\d{2}:\d{2}" -->
<!ELEMENT regexp (#PCDATA)>
<!-- Python functions to call after the data has been extracted with the regular
     expression. The functions are called in order of definition.-->
<!ELEMENT callbacks (callback+)> 
<!ELEMENT callback (#PCDATA)>
 <!-- a name is REQUIRED as an attribute when defining the function, and
      unnecessary when associated to a tag definition. Instead, the name MUST be
      mentioned as text between the <callback> tags. -->
 <!ATTLIST callback name CDATA #IMPLIED>
<!-- does a tag need to match a value before we should apply this normalizer ? -->
<!ELEMENT prerequisites (prereqTag+)> 
<!ELEMENT prereqTag (#PCDATA)>
 <!ATTLIST prereqTag name CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>

<!-- Define the patterns associated to this normalizer. -->
<!ELEMENT patterns (pattern+)> 
<!ELEMENT pattern (description?,text,tags,commonTags?,examples?)>
 <!-- a handy name for the pattern. Patterns are applied in alphabetical order
      of names.-->
 <!ATTLIST pattern name CDATA #REQUIRED>
<!-- a meta description of the log line covered by this pattern, for example
     <SYSLOGCODE>SYSLOGDATE SOURCE PROGRAM\[PID\]: BODY
     Regular expressions' metacharacters are not escaped by default, to provide
     their full power without the hassle.-->
<!ELEMENT text (#PCDATA)> 
<!-- The type of pattern. The default if type is not specified
     is a regexp pattern. "type" attribute can be "csv" to force normalizer engine
     to use csv python module in order to extract fields. The meta description
     for a csv pattern type must be as follow DATE,IP,USER,BODY where fields
     will be substitute by defined tags.-->
 <!ATTLIST text type CDATA #IMPLIED>
<!-- If attribute "type" is "csv" this attribute is used to define the csv separator.
     By default separator is a comma.-->
 <!ATTLIST text separator CDATA #IMPLIED>
<!-- If attribute "type" is "csv" this attribute is used to define the csv quotechar.
     By default quotechar is a quote.-->
 <!ATTLIST text quotechar CDATA #IMPLIED>
<!-- a list of real-life examples that can be used for auto-generating some
     documentation and unit testing. -->
<!ELEMENT examples (example+)> 
 <!ELEMENT example (description?,text,expectedTags)>
<!-- a (non necessarily complete) list of tags this normalizer will extract
     from this example. These tags must be present after normalizing the
     example for this normalizer to be considered valid.-->
<!ELEMENT expectedTags (expectedTag+)> 
 <!ELEMENT expectedTag (#PCDATA)>
  <!ATTLIST expectedTag name CDATA #REQUIRED>
<!-- A list of tags associated to the meta description in the pattern. -->
<!ELEMENT tags (tag+)> 
<!ELEMENT tag (description?,substitute,callbacks?)>
<!-- The name of the tag, as it will appear in the WallixLog. 
     if the name starts with '__' it is considered a temporary value (typically
     processed in callbacks) that will therefore not appear after normalization.-->
 <!ATTLIST tag name CDATA #REQUIRED> 
 <!-- the tag type, used to determine the regular expression that will be
      substituted in the pattern. It must be either a built-in tagType,
      or one defined in the current tagTypes markup. Newly defined tagTypes
      take precedence over built-in ones in case of a naming conflict. -->
 <!ATTLIST tag tagType CDATA "Anything"> 
<!-- The string chain that will be replaced by the tagType's regular
     expression in the pattern. -->
<!ELEMENT substitute (#PCDATA)>

<!-- If necessary, define here tags that must be set even though they weren't
     found in the pattern. -->
<!ELEMENT commonTags (commonTag+)> 
<!ELEMENT commonTag (#PCDATA)>
 <!ATTLIST commonTag name CDATA #REQUIRED>
 
<!-- If necessary, add here calls to callbacks to execute after
     the regular normalization. An arbitrary value argument set to 
     None will be passed to the callback. -->
<!ELEMENT finalCallbacks (callback+)>

=== wallix/pylogsparser/normalizers/VMWare_ESX4-ESXi4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!-- -->
<!-- pylogparser - Logs parsers python library -->
<!-- Copyright (C) 2011 Wallix Inc. -->
<!-- -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!-- -->
<!-- This package is free software; you can redistribute -->
<!-- it and/or modify it under the terms of the GNU Lesser -->
<!-- General Public License as published by the Free Software -->
<!-- Foundation; either version 2.1 of the License, or (at -->
<!-- your option) any later version. -->
<!-- -->
<!-- This package is distributed in the hope that it will be -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR -->
<!-- PURPOSE. See the GNU Lesser General Public License for -->
<!-- more details. -->
<!-- -->
<!-- You should have received a copy of the GNU Lesser General -->
<!-- Public License along with this package; if not, write -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place, -->
<!-- Suite 330, Boston, MA 02111-1307 USA -->
<!-- -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

<!DOCTYPE normalizer SYSTEM "normalizer.dtd">

<normalizer name="VMWare_ESX4-ESXi4"
	    version="0.99"
	    unicode="yes"
	    ignorecase="yes"
	    matchtype= "match"
	    appliedTo= "raw"
	    taxonomy="hypervisor">
  
  <description>
    <localized_desc language="en">This normalizer parses VMware ESX 4.x and ESXi 4.x logs that are not handled by the Syslog normalizer.</localized_desc>
    <localized_desc language="fr">Ce normaliseur analyse les logs de VMware ESX 4.x et ESXi 4.x. qui ne sont pas gérés pas le normaliseur Syslog.</localized_desc>
  </description>
  <authors>
    <author>clo@wallix.com</author>
  </authors>
  <tagTypes>
    <tagType name="date" type="datetime">
      <description>
	<localized_desc language="en">Expression matching a date in the format yyyy-mm-dd hh:mm:ss.</localized_desc>
	<localized_desc language="fr">Expression correspondant à une date au format yyyy-mm-dd hh:mm:ss.</localized_desc>
      </description>
      <regexp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}</regexp>
    </tagType>
    <tagType name="hexa_num" type="integer">
      <description>
	<localized_desc language="en">Expression matching a hexadecimal number.</localized_desc>
	<localized_desc language="fr">Expression correspondant à un nombre héxadécimal.</localized_desc>
      </description>
      <regexp>[A-F0-9]{8}</regexp>
    </tagType>
    <tagType name="alpha_words" type="basestring">
      <description>
	<localized_desc language="en">Expression matching the 'alpha' field, words between '.</localized_desc>
	<localized_desc language="fr">Expression correspondant au champ 'alpha', qui contient les mots entre '.</localized_desc>
      </description>
      <regexp>[^']+(?: [^']+)*</regexp>
    </tagType>
    <tagType name="level_word" type="basestring">
      <description>
	<localized_desc language="en">Expression matching the 'level' field.</localized_desc>
	<localized_desc language="fr">Expression correspondant au champ 'level'.</localized_desc>
      </description>
      <regexp>[^\s]+</regexp>
    </tagType>
  </tagTypes>
  <patterns>
     <pattern name="VMWare-001">
      <description>
	<localized_desc language="en">Logs contained in hostd.log file.</localized_desc>
	<localized_desc language="fr">Logs contenus dans le fichier hostd.log.</localized_desc>
      </description>
      <text>\[DATE NUMERIC LEVEL 'ALPHA'[^\]]*\] BODY</text>
      <tags>
	<tag name="__date" tagType="date">
	  <description>
	    <localized_desc language="en">The date on which the request was issued - please note that the timezone information is not carried over.</localized_desc>
	    <localized_desc language="fr">La date à laquelle la requête a été émise. Veuillez noter que l'information de fuseau horaire n'est pas prise en compte.</localized_desc>
	  </description>
	  <substitute>DATE</substitute>
	  <callbacks>
    	    <callback>YYYY-MM-DD hh:mm:ss</callback>
   	  </callbacks>
	</tag>
	<tag name="numeric" tagType="hexa_num">
	  <description>
	    <localized_desc language="en"></localized_desc>
	    <localized_desc language="fr"></localized_desc>
	  </description>
	  <substitute>NUMERIC</substitute>
	</tag>
	<tag name="level" tagType="level_word">
	  <description>
	    <localized_desc language="en">The level is the type of the log.</localized_desc>
	    <localized_desc language="fr">Le niveau correspond au type du log.</localized_desc>
	  </description>
	  <substitute>LEVEL</substitute>
	</tag>
	<tag name="alpha" tagType="alpha_words">
	  <description>
	    <localized_desc language="en"></localized_desc>
	    <localized_desc language="fr"></localized_desc>
	  </description>
	  <substitute>ALPHA</substitute>
	</tag>
	<tag name="body" tagType="Anything">
	  <description>
     	    <localized_desc language="en">The actual event message.</localized_desc>
     	    <localized_desc language="fr">Le message décrivant l'événement.</localized_desc>
	  </description>
	  <substitute>BODY</substitute>
	</tag>
      </tags>
      <examples>
	<example>
	  <text>[2011-09-05 17:03:15.220 F6F74B90 verbose 'App'] [VpxaMoVm::CheckMoVm] did not find a VM with ID 67 in the vmList</text>
	  <expectedTags>
	    <expectedTag name="numeric">F6F74B90</expectedTag>
	    <expectedTag name="level">verbose</expectedTag>
	    <expectedTag name="alpha">App</expectedTag>
	    <expectedTag name="body">[VpxaMoVm::CheckMoVm] did not find a VM with ID 67 in the vmList</expectedTag>
	    <expectedTag name="taxonomy">hypervisor</expectedTag>
	  </expectedTags>
	</example>
	<example>
	  <text>[2011-09-05 17:19:21.741 F63E6900 info 'Vmomi' opID=996867CC-0000030B] Throw vmodl.fault.RequestCanceled</text>
	  <expectedTags>
	    <expectedTag name="numeric">F63E6900</expectedTag>
	    <expectedTag name="level">info</expectedTag>
	    <expectedTag name="alpha">Vmomi</expectedTag>
	    <expectedTag name="body">Throw vmodl.fault.RequestCanceled</expectedTag>
	    <expectedTag name="taxonomy">hypervisor</expectedTag>
	  </expectedTags>
	</example>
      </examples>
    </pattern>
    <pattern name="VMWare-002">
      <description>
	<localized_desc language="en">Logs contained in sysboot.log file.</localized_desc>
	<localized_desc language="fr">Log contenu dans le fichier sysboot.log.</localized_desc>
      </description>
      <text>sysboot: EVENT</text>
      <tags>
	<tag name="body" tagType="Anything">
	  <description>
     	    <localized_desc language="en">The actual event message.</localized_desc>
     	    <localized_desc language="fr">Le message décrivant l'événement.</localized_desc>
	  </description>
	  <substitute>EVENT</substitute>
	</tag>
      </tags>
      <examples>
	<example>
	  <text>sysboot: Executing 'esxcfg-init --set-boot-progress done'</text>
	  <expectedTags>
	    <expectedTag name="body">Executing 'esxcfg-init --set-boot-progress done'</expectedTag>
	    <expectedTag name="taxonomy">hypervisor</expectedTag>
	  </expectedTags>
	</example>
      </examples>
    </pattern>
  </patterns>  
</normalizer>

=== wallix/pylogsparser/normalizers/squid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="squid"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="body">
    <description>        
        <localized_desc language="en">This normalizer parses messages issued by the Squid proxy server.
Please note that only Squid's "native log format" is supported by this normalizer.</localized_desc>
        <localized_desc language="fr">Ce normaliseur analyse les messages émis par les proxys Squid.
Seul le format "natif" des logs Squid est supporté par ce normaliseur.</localized_desc></description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <tagTypes>
        <tagType name="NoSpace" type="basestring">
            <description>        
        <localized_desc language="en">single lexeme without inner spaces</localized_desc>
        <localized_desc language="fr">unité sémantique sans espace intersticiel</localized_desc></description>
            <regexp>[^ ]+</regexp>
        </tagType>
    </tagTypes>
    <callbacks>
        <callback name="decode_epoch">
log["date"] = datetime.fromtimestamp(float(value))</callback>
        <callback name="decode_user">
if value != "-":
    log["user"] = value</callback>
    </callbacks>
    <patterns>
        <pattern name="squid-001">
            <description>        
        <localized_desc language="en">This pattern parses Squid's native log format.</localized_desc>
        <localized_desc language="fr">Cette structure décrit le format "natif" des logs Squid.</localized_desc></description>
            <text>EPOCH +ELAPSED IP CODE/REQUESTSTATUS SIZE METHOD URL USER PEERSTATUS/PEERHOST MIMETYPE</text>
            <tags>
                <tag name="__epoch" tagType="EpochTime">
                 <description>        
        <localized_desc language="en">the log EPOCH timestamp</localized_desc>
        <localized_desc language="fr">l'horodatage du log au format EPOCH</localized_desc></description>
                 <substitute>EPOCH</substitute>
                 <callbacks>
                  <callback>decode_epoch</callback>
                 </callbacks>
                </tag>
                <tag name="__user" tagType="NoSpace">
                 <description>        
        <localized_desc language="en">the user concerned by the request</localized_desc>
        <localized_desc language="fr">l'utilisateur concerné par la requête</localized_desc></description>
                 <substitute>USER</substitute>
                 <callbacks>
                  <callback>decode_user</callback>
                 </callbacks>
                </tag>
                <tag name="elapsed" tagType="Integer">
                 <description>        
        <localized_desc language="en">the elapsed time for the request</localized_desc>
        <localized_desc language="fr">le temps écoulé pour la requête</localized_desc></description>
                 <substitute>ELAPSED</substitute>
                </tag>
                <tag name="source_ip" tagType="IP">
                 <description>        
        <localized_desc language="en">the remote host's IP</localized_desc>
        <localized_desc language="fr">l'adresse IP de l'hôte distant</localized_desc></description>
                 <substitute>IP</substitute>
                </tag>
                <tag name="event_id" tagType="NoSpace">
                 <description>        
        <localized_desc language="en">the code returned by the proxy</localized_desc>
        <localized_desc language="fr">le code de la réponse émise par le proxy</localized_desc></description>
                 <substitute>CODE</substitute>
                </tag>
                <tag name="status" tagType="Integer">
                 <description>        
        <localized_desc language="en">the request's status</localized_desc>
        <localized_desc language="fr">le statut de la requête</localized_desc></description>
                 <substitute>REQUESTSTATUS</substitute>
                </tag>
                <tag name="len" tagType="Integer">
                 <description>        
        <localized_desc language="en">the size of the request's result</localized_desc>
        <localized_desc language="fr">la taille du résultat de la requête</localized_desc></description>
                 <substitute>SIZE</substitute>
                </tag>
                <tag name="method" tagType="NoSpace">
                 <description>        
        <localized_desc language="en">the request's method</localized_desc>
        <localized_desc language="fr">la méthode associée à la requête</localized_desc></description>
                 <substitute>METHOD</substitute>
                </tag>
                <tag name="url" tagType="URL">
                 <description>        
        <localized_desc language="en">the requested URL</localized_desc>
        <localized_desc language="fr">l'URL requêtée</localized_desc></description>
                 <substitute>URL</substitute>
                </tag>
                <tag name="peer_status" tagType="NoSpace">
                 <description>        
        <localized_desc language="en">the peer's status</localized_desc>
        <localized_desc language="fr">le statut du pair</localized_desc></description>
                 <substitute>PEERSTATUS</substitute>
                </tag>
                <tag name="peer_host" tagType="NoSpace">
                 <description>        
        <localized_desc language="en">the peer's host</localized_desc>
        <localized_desc language="fr">l'hôte du pair</localized_desc></description>
                 <substitute>PEERHOST</substitute>
                </tag>
                <tag name="mime_type" tagType="NoSPace">
                 <description>        
        <localized_desc language="en">the MIME type of the result of the request</localized_desc>
        <localized_desc language="fr">le type MIME du résultat de la requête</localized_desc></description>
                 <substitute>MIMETYPE</substitute>
                </tag>
            </tags>
            <examples>
                <example>
                     <text>1259844091.407    307 82.238.42.70 TCP_MISS/200 1015 GET http://www.ietf.org/css/ietf.css fbo DIRECT/64.170.98.32 text/css</text>
                     <expectedTags>
                          <expectedTag name="event_id">TCP_MISS</expectedTag>
                          <expectedTag name="elapsed">307</expectedTag>
                          <expectedTag name="source_ip">82.238.42.70</expectedTag>
                          <expectedTag name="method">GET</expectedTag>
                          <expectedTag name="mime_type">text/css</expectedTag>
                          <expectedTag name="peer_host">64.170.98.32</expectedTag>
                          <expectedTag name="peer_status">DIRECT</expectedTag>
                          <expectedTag name="len">1015</expectedTag>
                          <expectedTag name="status">200</expectedTag>
                          <expectedTag name="url">http://www.ietf.org/css/ietf.css</expectedTag>
                          <expectedTag name="user">fbo</expectedTag>
                     </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
    <commonTags>
        <commonTag name="program">squid</commonTag>
    </commonTags>
</normalizer>

=== wallix/pylogsparser/normalizers/RefererParser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="RefererParser"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="request_header_referer_contents">
    <description>
        <localized_desc language="en">This normalizer extracts additional info from URLs such as domain, protocol, etc.</localized_desc>
        <localized_desc language="fr">Ce normaliseur extrait des données supplémentaires à partir des URLs telles que le domaine, le protocole, etc.</localized_desc>
    </description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <callbacks>
        <callback name="decodeURL">
parsed = urlparse.urlparse(value)
if parsed.hostname:
    log['referer_hostname'] = parsed.hostname
    log['referer_domain'] = extras.get_domain(parsed.hostname)
if parsed.path:
    log['referer_path'] = parsed.path
</callback>
    </callbacks>
    <patterns>
        <pattern name="URLPattern">
            <text>URL</text>
            <tags>
                <tag name="__url" tagType="Anything">
                    <substitute>URL</substitute>
                    <callbacks>
                        <callback>decodeURL</callback>
                    </callbacks>
                </tag>
            </tags>
            <examples>
                <example>
                     <text>http://www.wallix.org/2011/09/20/how-to-use-linux-containers-lxc-under-debian-squeeze/</text>
                     <expectedTags>
                          <expectedTag name="referer_hostname">www.wallix.org</expectedTag>
                          <expectedTag name="referer_path">/2011/09/20/how-to-use-linux-containers-lxc-under-debian-squeeze/</expectedTag>
                          <expectedTag name="referer_domain">wallix.org</expectedTag>
                     </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
</normalizer>
