=== wallix/pylogsparser/normalizers/normalizer.dtd
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!ELEMENT normalizer (description?,authors?,tagTypes?,callbacks?,prerequisites?,patterns,commonTags?,finalCallbacks?)>
 <!-- The given name of the normalizer -->
 <!ATTLIST normalizer name CDATA #REQUIRED>
 <!-- The version of this normalizer -->
 <!ATTLIST normalizer version CDATA #REQUIRED>
 <!-- Compile the associated regexps with the UNICODE flag -->
 <!ATTLIST normalizer unicode (no|yes) "yes">
 <!-- Compile the associated regexps with the IGNORECASE flag -->
 <!ATTLIST normalizer ignorecase (no|yes) "yes">
 <!-- Patterns are multiline -->
 <!ATTLIST normalizer multiline (no|yes) "yes">
 <!-- how to match the pattern : "match" to match at the beginning of the sample,
      or "search" to match anywhere in the sample -->
 <!ATTLIST normalizer matchtype (match|search) "match">
 <!-- What tag will the patterns be applied to ? Set the value to "raw" for
      protocol normalizers, "body" for application or generic normalizers -->
 <!ATTLIST normalizer appliedTo CDATA #REQUIRED>
<!-- A set of descriptions, language is specified as the usual language code -->
 <!-- The service taxonomy, if relevant, of the normalizer. See README.rst -->
 <!ATTLIST normalizer taxonomy CDATA #IMPLIED>
  <!-- set to yes if a space in the patterns should be considered as a combination 
      of any whitespace character, for readability of the patterns.-->
 <!ATTLIST normalizer  expandWhitespaces (yes|no) "no">
<!ELEMENT description (localized_desc+)>
 <!ELEMENT localized_desc (#PCDATA)>
 <!ATTLIST localized_desc language CDATA #REQUIRED>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>

<!-- Here one can define specific regexp blocks (this should be rare, with 
     most cases being covered by default tagTypes.). Once extracted, the result
     is passed to the callbacks in order. -->
<!ELEMENT tagTypes (tagType+)>
<!ELEMENT tagType (description?,regexp)>
 <!-- the name of the tag type preferably in camelCase, for example
      "syslogDate", "EPOCH", "IP", etc -->
 <!ATTLIST tagType name CDATA #REQUIRED>
 <!-- The expected python type of the extracted value once the callbacks
      have been fired. Not used yet, might be in the future. -->
 <!ATTLIST tagType type (integer|float|basestring|datetime) "basestring">
<!-- the regular expression the data must match to qualify, for example
     "[A-Z][a-z]{2} [ 0-9]\d \d{2}:\d{2}:\d{2}" -->
<!ELEMENT regexp (#PCDATA)>
<!-- Python functions to call after the data has been extracted with the regular
     expression. The functions are called in order of definition.-->
<!ELEMENT callbacks (callback+)> 
<!ELEMENT callback (#PCDATA)>
 <!-- a name is REQUIRED as an attribute when defining the function, and
      unnecessary when associated to a tag definition. Instead, the name MUST be
      mentioned as text between the <callback> tags. -->
 <!ATTLIST callback name CDATA #IMPLIED>
<!-- does a tag need to match a value before we should apply this normalizer ? -->
<!ELEMENT prerequisites (prereqTag+)> 
<!ELEMENT prereqTag (#PCDATA)>
 <!ATTLIST prereqTag name CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>

<!-- Define the patterns associated to this normalizer. -->
<!ELEMENT patterns (pattern+)> 
<!ELEMENT pattern (description?,text,tags,commonTags?,examples?)>
 <!-- a handy name for the pattern. Patterns are applied in alphabetical order
      of names.-->
 <!ATTLIST pattern name CDATA #REQUIRED>
<!-- a meta description of the log line covered by this pattern, for example
     <SYSLOGCODE>SYSLOGDATE SOURCE PROGRAM\[PID\]: BODY
     Regular expressions' metacharacters are not escaped by default, to provide
     their full power without the hassle.-->
<!ELEMENT text (#PCDATA)> 
<!-- The type of pattern. The default if type is not specified
     is a regexp pattern. "type" attribute can be "csv" to force normalizer engine
     to use csv python module in order to extract fields. The meta description
     for a csv pattern type must be as follow DATE,IP,USER,BODY where fields
     will be substitute by defined tags.-->
 <!ATTLIST text type CDATA #IMPLIED>
<!-- If attribute "type" is "csv" this attribute is used to define the csv separator.
     By default separator is a comma.-->
 <!ATTLIST text separator CDATA #IMPLIED>
<!-- If attribute "type" is "csv" this attribute is used to define the csv quotechar.
     By default quotechar is a quote.-->
 <!ATTLIST text quotechar CDATA #IMPLIED>
<!-- a list of real-life examples that can be used for auto-generating some
     documentation and unit testing. -->
<!ELEMENT examples (example+)> 
 <!ELEMENT example (description?,text,expectedTags)>
<!-- a (non necessarily complete) list of tags this normalizer will extract
     from this example. These tags must be present after normalizing the
     example for this normalizer to be considered valid.-->
<!ELEMENT expectedTags (expectedTag+)> 
 <!ELEMENT expectedTag (#PCDATA)>
  <!ATTLIST expectedTag name CDATA #REQUIRED>
<!-- A list of tags associated to the meta description in the pattern. -->
<!ELEMENT tags (tag+)> 
<!ELEMENT tag (description?,substitute,callbacks?)>
<!-- The name of the tag, as it will appear in the WallixLog. 
     if the name starts with '__' it is considered a temporary value (typically
     processed in callbacks) that will therefore not appear after normalization.-->
 <!ATTLIST tag name CDATA #REQUIRED> 
 <!-- the tag type, used to determine the regular expression that will be
      substituted in the pattern. It must be either a built-in tagType,
      or one defined in the current tagTypes markup. Newly defined tagTypes
      take precedence over built-in ones in case of a naming conflict. -->
 <!ATTLIST tag tagType CDATA "Anything"> 
<!-- The string chain that will be replaced by the tagType's regular
     expression in the pattern. -->
<!ELEMENT substitute (#PCDATA)>

<!-- If necessary, define here tags that must be set even though they weren't
     found in the pattern. -->
<!ELEMENT commonTags (commonTag+)> 
<!ELEMENT commonTag (#PCDATA)>
 <!ATTLIST commonTag name CDATA #REQUIRED>
 
<!-- If necessary, add here calls to callbacks to execute after
     the regular normalization. An arbitrary value argument set to 
     None will be passed to the callback. -->
<!ELEMENT finalCallbacks (callback+)>

=== wallix/pylogsparser/normalizers/LEA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!-- http://updates.checkpoint.com/fileserver/ID/7460/FILE/LEA_fields_draft.pdf   -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
 
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="LEA"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="body"
            taxonomy="firewall">
    <description>
        <localized_desc language="en">This normalizer parses Check Point's LEA (Log Export API) formatted logs. The LEA format is used by Check Point products to export logs to a LogBox.
The formatting with | as a fields separator is due to the use of FW1-LogGrabber for log fetching.

Due to the dynamic nature of this logging format, please refer to your product's documentation to find out more about tagging.</localized_desc>
        <localized_desc language="fr">Ce normaliseur analyse les logs émis en utilisant l'API Check Point d'export de logs (LEA). Cette API peut être utilisée pour la réception de logs en provenance d'équipements Check Point.
Le formatage des champs séparés par le caractère | est dû à la récupération des logs via l'utilitaire FW1-LogGrabber.

En raison de la nature dynamique de ce format de log, les tags extraits peuvent varier en fonction des événements consignés. Veuillez vous référer à la documentation de votre équipement exposant LEA pour de plus amples informations.</localized_desc></description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <tagTypes>
        <tagType name="LEAFields" type="basestring">
            <description>
        <localized_desc language="en">LEA fields as "key=value", separated by |</localized_desc>
        <localized_desc language="fr">Champs descriptifs au format "clé=valeur", séparés par le caractère |</localized_desc></description>
            <regexp>[^ =]+=[^=|]+[|](?:[^ =]+=[^|]+|)*[^ =]+=[^|]+</regexp>
        </tagType>
    </tagTypes>
    <callbacks>
        <callback name="decode_LEA">
# These are the only tags we extract
KNOWN = [ ("loc", "id"),
          "product",
          "i/f_dir",
          "i/f_name",
          "orig",
          "type",
          "action",
          ("proto", "protocol"),
          "rule",
          "src",
          "dst",
          ("s_port", "source_port"),
          ("service", "dest_port"),
          ("uuid", "lea_uuid") ]

def src_dst_extract(data):
    ip_re = re.compile("(?&lt;![.0-9])((?:[0-9]{1,3}[.]){3}[0-9]{1,3})(?![.0-9])")
    if ip_re.match(data['src']):
        data['source_ip'] = data['src']
    else:
        data['source_host'] = data['src']
    if ip_re.match(data['dst']):
        data['dest_ip'] = data['dst']
    else:
        data['dest_host'] = data['dst']
    if ip_re.match(data['orig']):
        data['local_ip'] = data['orig']
    else:
        data['local_host'] = data['orig']
    del data['src']
    del data['dst']
    del data['orig']

def int_extract(data):
    if 'i/f_dir' in data.keys():
        if data['i/f_dir'] == 'inbound':
            data['inbound_int'] = data['i/f_name']
        if data['i/f_dir'] == 'outbound':
            data['outbound_int'] = data['i/f_name']
    del data['i/f_dir']
    del data['i/f_name']

dic = {}
body = value.split('|')
for l in body:
    key, val = l.split("=", 1)
    dic[key] = val
# keep only known tags
for t in KNOWN:
    if isinstance(t, basestring):
       t = (t,t)
    old, new = t
    if old in dic.keys():
        log[new] = dic[old]
# improve body readability
log['body'] = log['body'].replace("|", " ") 
# Try to retrieve the date
try:
    log['date'] = datetime.utcfromtimestamp(int(dic['time']))
except:
    try:
        log['date'] = datetime.strptime(dic['time'], "%Y-%m-%d %H:%M:%S")
    except:
        # cannot parse it, keep it safe
        log['time'] = dic['time']

src_dst_extract(log)
int_extract(log)

</callback>
    </callbacks>
    <prerequisites>
        <prereqTag name="program">lea</prereqTag>
    </prerequisites>
    <patterns>
        <pattern name="LEA-001">
            <description>
        <localized_desc language="en">A list of key-value couples, separated by a | character.</localized_desc>
        <localized_desc language="fr">L'événement est décrit à l'aide d'une série de couples clé-valeur, séparés par le caractère |.</localized_desc></description>
            <text>LEAFIELDS</text>
            <tags>
                <tag name="__lea" tagType="LEAFields">
                 <description>
        <localized_desc language="en">a list of key-value couples, separated by a | character, needing some post-processing</localized_desc>
        <localized_desc language="fr">la liste des couples clé-valeur, nécessitant un traitement ultérieur</localized_desc></description>
                 <substitute>LEAFIELDS</substitute>
                 <callbacks>
                  <callback>decode_LEA</callback>
                 </callbacks>
                </tag>
            </tags>
            <examples>
                <example>
                     <text>loc=3707|time=1199716450|action=accept|orig=fw1|i/f_dir=inbound|i/f_name=PCnet1|has_accounting=0|uuid=&lt;47822e42,00000001,7b040a0a,000007b6&gt;|product=VPN-1 &amp; FireWall-1|__policy_id_tag=product=VPN-1 &amp; FireWall-1[db_tag={9F95C344-FE3F-4E3E-ACD8-60B5194BAAB4};mgmt=fw1;date=1199701916;policy_name=Standard]|src=naruto|s_port=56840|dst=fw1|service=https|proto=tcp|rule=1</text>
                     <expectedTags>
                          <expectedTag name="id">3707</expectedTag>
                          <expectedTag name="action">accept</expectedTag>
                          <expectedTag name="product">VPN-1 &amp; FireWall-1</expectedTag>
                          <expectedTag name="inbound_int">PCnet1</expectedTag>
                          <expectedTag name="local_host">fw1</expectedTag>
                          <expectedTag name="protocol">tcp</expectedTag>
                          <expectedTag name="rule">1</expectedTag>
                          <expectedTag name="source_host">naruto</expectedTag>
                          <expectedTag name="dest_host">fw1</expectedTag>
                          <expectedTag name="source_port">56840</expectedTag>
                          <expectedTag name="dest_port">https</expectedTag>
                          <expectedTag name="taxonomy">firewall</expectedTag>
                     </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
</normalizer>

=== wallix/pylogsparser/normalizers/sshd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="sshd"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="body"
            taxonomy="access control">
    <description><localized_desc language="en">This normalizer parses connection messages logged by a SSH server.</localized_desc>
        <localized_desc language="fr">Ce normaliseur analyse les événements de connexion à un serveur SSH.</localized_desc></description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <tagTypes>
        <tagType name="ActionTag" type="basestring">
            <description>
        <localized_desc language="en">matches the action logged for a connection</localized_desc>
        <localized_desc language="fr">correspond à l'action de connexion</localized_desc></description>
            <regexp>Failed|Accepted</regexp>
        </tagType>
    </tagTypes>
    <callbacks>
        <callback name="decode_action">
if value == "Failed":
    log['action'] = 'fail'
else:
    log['action'] = 'accept'</callback>
    </callbacks>
    <patterns>
        <pattern name="sshd-001">
            <description>
        <localized_desc language="en">A generic sshd log line.</localized_desc>
        <localized_desc language="fr">Une ligne de log standard émise par un serveur SSH.</localized_desc></description>
            <text>ACTION METHOD for(?: invalid user)? USER from IP port [0-9]+ ssh[0-9]</text>
            <tags>
                <tag name="__action" tagType="ActionTag">
                 <description>
        <localized_desc language="en">the outcome of the connection attempt</localized_desc>
        <localized_desc language="fr">le résultat de la tentative de connexion</localized_desc></description>
                 <substitute>ACTION</substitute>
                 <callbacks>
                  <callback>decode_action</callback>
                 </callbacks>
                </tag>
                <tag name="method" tagType="Anything">
                 <description>
        <localized_desc language="en">the connection method (password or key)</localized_desc>
        <localized_desc language="fr">la méthode de connexion utilisée (mot de passe ou clé asymétrique)</localized_desc></description>
                 <substitute>METHOD</substitute>
                </tag>
                <tag name="user" tagType="Anything">
                 <description>
        <localized_desc language="en">the user requesting the connection</localized_desc>
        <localized_desc language="fr">l'utilisateur à l'origine de la connexion</localized_desc></description>
                 <substitute>USER</substitute>
                </tag>
                <tag name="source_ip" tagType="IP">
                 <description>
        <localized_desc language="en">the inbound connection's IP address</localized_desc>
        <localized_desc language="fr">l'IP entrante de la connexion</localized_desc></description>
                 <substitute>IP</substitute>
                </tag>
            </tags>
            <examples>
                <example>
                     <text>Failed password for admin from 218.49.183.17 port 49468 ssh2</text>
                     <expectedTags>
                          <expectedTag name="action">fail</expectedTag>
                          <expectedTag name="method">password</expectedTag>
                          <expectedTag name="user">admin</expectedTag>
                          <expectedTag name="source_ip">218.49.183.17</expectedTag>
                          <expectedTag name="taxonomy">access control</expectedTag>
                     </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
</normalizer>

=== wallix/pylogsparser/normalizers/postfix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- pylogparser - Logs parsers python library                  -->
<!-- Copyright (C) 2011 Wallix Inc.                             -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--                                                            -->
<!-- This package is free software; you can redistribute        -->
<!-- it and/or modify it under the terms of the GNU Lesser      -->
<!-- General Public License as published by the Free Software   -->
<!-- Foundation; either version 2.1 of the License, or (at      -->
<!-- your option) any later version.                            -->
<!--                                                            -->
<!-- This package is distributed in the hope that it will be    -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied -->
<!-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    -->
<!-- PURPOSE.  See the GNU Lesser General Public License for    -->
<!-- more details.                                              -->
<!--                                                            -->
<!-- You should have received a copy of the GNU Lesser General  -->
<!-- Public License along with this package; if not, write      -->
<!-- to the Free Software Foundation, Inc., 59 Temple Place,    -->
<!-- Suite 330, Boston, MA  02111-1307  USA                     -->
<!--                                                            -->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!DOCTYPE normalizer SYSTEM "normalizer.dtd">
<normalizer name="postfix"
            version="0.99"
            unicode="yes"
            ignorecase="yes"
            matchtype="match"
            appliedTo="body"
            taxonomy="mail">
    <description>
        <localized_desc language="en">Postfix log normalization.
Postfix logs consist of a message UID and a list of keys and values.
Normalized keys are "client", "to", "from", "orig_to", "relay", "size", "message-id" and "status".</localized_desc>
        <localized_desc language="fr">Ce normaliseur analyse les logs émis par le service Postfix.
Les messages Postfix sont composés d'un UID de message et d'une liste variable de clés et de valeurs associées.
Les clés extraites par ce normaliseur sont "client", "to", "from", "orig_to", "relay", "size", "message-id" et "status".</localized_desc>
    </description>
    <authors>
        <author>mhu@wallix.com</author>
    </authors>
    <tagTypes>
        <tagType name="postfixUID" type="basestring">
            <description>
        <localized_desc language="en">the hexadecimal message UID</localized_desc>
        <localized_desc language="fr">l'UID associé au message, exprimé sous forme d'un nombre hexadécimal</localized_desc></description>
            <regexp>[0-9A-F]{11}</regexp>
        </tagType>
    </tagTypes>
    <callbacks>
        <callback name="decode_postfix_key_value">
# find the component and trim the program
if log.get("program", "").startswith("postfix"):
    log["component"] = log['program'][8:]
    log["program"] = "postfix"
ACCEPTED = [ "client",
             "to",
             "from",
             "orig_to",
             "relay",
             "size",
             "message-id",
             "status" ]
# re to trying to match client and relay address
r=re.compile('(?P&lt;host&gt;[A-Za-z0-9\-\.]+)(?P&lt;ip&gt;\[.*\])?(?P&lt;port&gt;\:\d+)?$')

couples = value.split(', ')
for couple in couples:
    tagname, tagvalue = couple.split('=', 1)
    if tagname in ACCEPTED:
        tagvalue = tagvalue.strip('&lt;&gt;')
        log[tagname] = tagvalue
        if tagname == 'status':
            log[tagname] = log[tagname].split()[0]

TRANSLATE = {"to": "message_recipient",
             "from": "message_sender",
             "size": "len",
             "message-id": "message_id"}
for k,v in TRANSLATE.items():
    if k in log.keys():
        val = log[k]
        del log[k]
        log[v] = val

if 'client' in log.keys():
    host, ip, port = r.match(log['client']).groups()
    if host:
        log['source_host'] = host
    if ip:
        log['source_ip'] = ip.strip("[]")
    if port:
        log['source_port'] = port.strip(':')

if 'relay' in log.keys():
    host, ip, port = r.match(log['relay']).groups()
    if host:
        log['dest_host'] = host
    if ip:
        log['dest_ip'] = ip.strip("[]")
    if port:
        log['dest_port'] = port.strip(':')

    </callback>
    </callbacks>
    <prerequisites>
        <prereqTag name="program">postfix.+</prereqTag>
    </prerequisites>
    <patterns>
        <pattern name="postfix-001">
            <description>
        <localized_desc language="en">Generic postfix message with an UID and many key-values couples.</localized_desc>
        <localized_desc language="fr">Message Postfix générique comportant un UID et plusieurs couples clé-valeur.</localized_desc></description>
            <text>UID: KEYVALUES</text>
            <tags>
                <tag name="queue_id" tagType="postfixUID">
                 <description>
        <localized_desc language="en">the Postfix message UID</localized_desc>
        <localized_desc language="fr">l'UID du message Postfix</localized_desc></description>
                 <substitute>UID</substitute>
                </tag>
                <tag name="__keyvalues" tagType="Anything">
                 <description>
        <localized_desc language="en">the Postfix key-value couples</localized_desc>
        <localized_desc language="fr">les couples clé-valeur du log Postfix</localized_desc></description>
                 <substitute>KEYVALUES</substitute>
                 <callbacks>
                  <callback>decode_postfix_key_value</callback>
                 </callbacks>
                </tag>
            </tags>
            <examples>
                <example>
                     <text>74275790B06: to=&lt;root@ubuntu&gt;, orig_to=&lt;root&gt;, relay=none, delay=0.91, delays=0.31/0.07/0.53/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=ubuntu type=A: Host not found)</text>
                     <expectedTags>
                          <expectedTag name="queue_id">74275790B06</expectedTag>
                          <expectedTag name="message_recipient">root@ubuntu</expectedTag>
                          <expectedTag name="orig_to">root</expectedTag>
                          <expectedTag name="relay">none</expectedTag>
                          <expectedTag name="status">bounced</expectedTag>
                          <expectedTag name="taxonomy">mail</expectedTag>
                     </expectedTags>
                </example>
            </examples>
        </pattern>
    </patterns>
</normalizer>
